sudo: required #permission
services:
  - docker

before_install:
  - docker build -t samidocker93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samidocker93/react-test npm run test -- --coverage #coverage to exit tests suits

after_success:
  - docker build -t samidocker93/multi-client:latest ./client
  - docker build -t samidocker93/multi-nginx:latest ./nginx
  - docker build -t samidocker93/multi-server:latest ./server
  - docker build -t samidocker93/multi-worker:latest ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samidocker93/multi-client:latest
  - docker push samidocker93/multi-nginx:latest
  - docker push samidocker93/multi-server:latest
  - docker push samidocker93/multi-worker:latest

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-787114486602"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY